# Build nugets and publish them to nuget.org

name: Publish nugets

on:
  workflow_dispatch:
    inputs:
        name:
          description: "Name the release"
          default: "Latest"

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'naf.sln'
      PROJECT: 'src/Naf.Filtering/Naf.Filtering.csproj'

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Hello Step
      run: echo "Hello ${{ github.event.inputs.name }}"
            
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString "1.0.${{github.run_number}}"
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

 #   - name: Build
 #     run: dotnet build $PROJECT --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Build
      run: dotnet pack $SOLUTION --configuration $BUILD_CONFIG -p:PackageVersion=$BUILD_VERSION --no-restore --output nupkgs

  #  - name: Publish
  #    if: startsWith(github.ref, 'refs/heads/release')
  #    run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

# /home/runner/work/naf/naf/src/Naf.Filtering/bin/Release/Naf.Filtering.1.0.0-build.nupkg
#--output nupkgs    

    - name: Publish the package to nuget.org
      run: dotnet nuget push **\*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
